/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-01-21 06:41:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/workspace/semiTeam/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1736127166320L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>FILMRADER</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("	<header>\r\n");
      out.write("    <!-- 왼쪽: 이미지와 사이트 이름 -->\r\n");
      out.write("    <a href=\"#\" class=\"logo\">\r\n");
      out.write("        <img src=\"resources/images/logo.png\" alt=\"로고\">\r\n");
      out.write("        <span>FILMRADER</span>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("    <main>\r\n");
      out.write("        <!-- 왼쪽: 네비게이션 -->\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <!-- 토글 버튼 추가 -->\r\n");
      out.write("                <button id=\"toggle-btn\">\r\n");
      out.write("                    <img src=\"resources/images/icons8-toggle-off.png\" alt=\"Toggle\" id=\"toggle-icon\">\r\n");
      out.write("                </button> \r\n");
      out.write("\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <img src=\"resources/images/icons8-home-icon.png\" alt=\"Home\">\r\n");
      out.write("                        <span>Home</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/movie/discovery\">\r\n");
      out.write("                        <img src=\"resources/images/icons8-discover-icon.png\" alt=\"Discovery\">\r\n");
      out.write("                        <span>Discover</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"html/community.html\">\r\n");
      out.write("                        <img src=\"resources/images/icons8-community-icon.png\" alt=\"Community\">\r\n");
      out.write("                        <span>Community</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <img src=\"resources/images/icons8-top-movies-ion.png\" alt=\"Top Movies\">\r\n");
      out.write("                        <span>Top Movies</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"html/detailpage.html\">\r\n");
      out.write("                        <img src=\"resources/images/icons8-New-icon.png\" alt=\"New Releases\">\r\n");
      out.write("                        <span>New Releases</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    \r\n");
      out.write("        <!-- 오른쪽: 콘텐츠 -->\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <!-- 상단 배너 캐러셀 -->\r\n");
      out.write("            <section class=\"banner-carousel\">\r\n");
      out.write("                <div class=\"banner-carousel-container\">\r\n");
      out.write("                    <div class=\"banner-carousel-slide\">\r\n");
      out.write("                        <img src=\"resources/images/banner1.jpg\" alt=\"배너 1\">\r\n");
      out.write("                        <img src=\"resources/images/banner2.jpg\" alt=\"배너 2\">\r\n");
      out.write("                        <img src=\"resources/images/banner3.jpg\" alt=\"배너 3\">\r\n");
      out.write("                        <img src=\"resources/images/banner4.jpg\" alt=\"배너 4\">\r\n");
      out.write("                        <img src=\"resources/images/banner5.jpg\" alt=\"배너 5\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"banner-carousel-prev\">&#10094;</button>\r\n");
      out.write("                    <button class=\"banner-carousel-next\">&#10095;</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("            <!-- 하단 인기 영화 캐러셀 -->\r\n");
      out.write("            <section class=\"popular-movies\">\r\n");
      out.write("                <h2>인기 영화</h2>\r\n");
      out.write("                <div class=\"movie-carousel\">\r\n");
      out.write("                    <div class=\"movie-carousel-slide\">\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie1.jpg\" alt=\"영화 1\">\r\n");
      out.write("                            <p>영화 제목 1</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie2.jpg\" alt=\"영화 2\">\r\n");
      out.write("                            <p>영화 제목 2</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie3.jpg\" alt=\"영화 3\">\r\n");
      out.write("                            <p>영화 제목 3</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie4.jpg\" alt=\"영화 4\">\r\n");
      out.write("                            <p>영화 제목 4</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie5.jpg\" alt=\"영화 5\">\r\n");
      out.write("                            <p>영화 제목 5</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie6.jpg\" alt=\"영화 6\">\r\n");
      out.write("                            <p>영화 제목 6</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie7.jpg\" alt=\"영화 7\">\r\n");
      out.write("                            <p>영화 제목 7</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie8.jpg\" alt=\"영화 8\">\r\n");
      out.write("                            <p>영화 제목 8</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie9.jpg\" alt=\"영화 9\">\r\n");
      out.write("                            <p>영화 제목 9</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"movie-carousel-prev\">\r\n");
      out.write("                        <img src=\"resources/images/left-icon.png\" alt=\"\">\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button class=\"movie-carousel-next\">\r\n");
      out.write("                        <img src=\"resources/images/right-icon.png\" alt=\"\">\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            <!-- 최신 영화 캐러셀 -->\r\n");
      out.write("            <section class=\"new-releases\">\r\n");
      out.write("                <h2>최신 영화</h2>\r\n");
      out.write("                <div class=\"movie-carousel\">\r\n");
      out.write("                    <div class=\"movie-carousel-slide\">\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie10.jpg\" alt=\"영화 10\">\r\n");
      out.write("                            <p>영화 제목 10</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie11.jpg\" alt=\"영화 11\">\r\n");
      out.write("                            <p>영화 제목 11</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie12.jpg\" alt=\"영화 12\">\r\n");
      out.write("                            <p>영화 제목 12</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie13.jpg\" alt=\"영화 13\">\r\n");
      out.write("                            <p>영화 제목 13</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie14.jpg\" alt=\"영화 14\">\r\n");
      out.write("                            <p>영화 제목 14</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie15.jpg\" alt=\"영화 15\">\r\n");
      out.write("                            <p>영화 제목 15</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie16.jpg\" alt=\"영화 16\">\r\n");
      out.write("                            <p>영화 제목 16</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie17.jpg\" alt=\"영화 17\">\r\n");
      out.write("                            <p>영화 제목 17</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-item\">\r\n");
      out.write("                            <img src=\"resources/images/movie18.jpg\" alt=\"영화 18\">\r\n");
      out.write("                            <p>영화 제목 18</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"movie-carousel-prev\">\r\n");
      out.write("                        <img src=\"resources/images/left-icon.png\" alt=\"\">\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button class=\"movie-carousel-next\">\r\n");
      out.write("                        <img src=\"resources/images/right-icon.png\" alt=\"\">\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <p>&copy; 2025 FILMRADER. All rights reserved.</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"resources/js/header.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("        ");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\r\n");
        out.write("        ");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /index.jsp(25,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                <!-- 오른쪽: 검색, 로그인, 회원가입 -->\r\n");
        out.write("                <div class=\"header-right\">\r\n");
        out.write("                    <div class=\"search-container\">\r\n");
        out.write("                        <input type=\"text\" class=\"search-input\" id=\"searchInput\" placeholder=\"Search...\">\r\n");
        out.write("                        <img src=\"resources/images/search-icon.png\" alt=\"검색\" class=\"search-icon\" id=\"searchIcon\">\r\n");
        out.write("                    </div>\r\n");
        out.write("                    <a href=\"login\" class=\"login-btn\">로그인</a>\r\n");
        out.write("                    <a href=\"signUp\" class=\"signup-btn\">회원가입</a>\r\n");
        out.write("                </div>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("            <!-- 오른쪽: 검색, 알림, 프로필 -->\r\n");
        out.write("            <div class=\"header-right\">\r\n");
        out.write("                <div class=\"search-container\">\r\n");
        out.write("                    <input type=\"text\" class=\"search-input\" id=\"searchInput2\" placeholder=\"Search...\">\r\n");
        out.write("                    <img src=\"resources/images/search-icon.png\" alt=\"검색\" class=\"search-icon\" id=\"searchIcon2\">\r\n");
        out.write("                </div>\r\n");
        out.write("                <div class=\"notification\">\r\n");
        out.write("                    <img src=\"resources/images/bell.png\">\r\n");
        out.write("                </div>\r\n");
        out.write("                <div>\r\n");
        out.write("                    <img src=\"#\">프로필 이미지 + 닉네임\r\n");
        out.write("                </div>\r\n");
        out.write("            </div>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }
}
