-- 회원 테이블 생성
CREATE TABLE SITE_USER(
   USER_NO   NUMBER PRIMARY KEY,
   USER_ID   VARCHAR2(50)   NOT NULL,
   USER_PW   VARCHAR2(50)   NOT NULL,
   USER_NM   VARCHAR2(30)   NOT NULL,
   USER_EMAIL   VARCHAR2(100)   NOT NULL,
   USER_DT   DATE DEFAULT SYSDATE NOT NULL,
   SECESSION_FL   CHAR(1)   DEFAULT 'N' NOT NULL,
   USER_NICK   VARCHAR2(50)   NOT NULL,
   USER_MBTI   VARCHAR2(15)   NOT NULL,
   USER_ADDR   VARCHAR2(500)   NULL,
   PROFILE_IMG   VARCHAR2(500)   NULL,
   GENDER   CHAR(1)   NOT NULL,
   BIRTH_DT   DATE   NOT NULL
);

-- 회원 테이블에 대한 커멘트
COMMENT ON COLUMN SITE_USER.USER_NO IS '회원 번호';
COMMENT ON COLUMN SITE_USER.USER_ID IS '회원 아이디';
COMMENT ON COLUMN SITE_USER.USER_PW IS '회원 비밀번호';
COMMENT ON COLUMN SITE_USER.USER_NM IS '회원 이름';
COMMENT ON COLUMN SITE_USER.USER_EMAIL IS '회원 이메일';
COMMENT ON COLUMN SITE_USER.USER_DT IS '회원 가입일';
COMMENT ON COLUMN SITE_USER.SECESSION_FL IS '회원 탈퇴 여부';
COMMENT ON COLUMN SITE_USER.USER_NICK IS '회원 닉네임';
COMMENT ON COLUMN SITE_USER.USER_MBTI IS '회원 MBTI';
COMMENT ON COLUMN SITE_USER.USER_ADDR IS '회원 주소';
COMMENT ON COLUMN SITE_USER.PROFILE_IMG IS '프로필 이미지';
COMMENT ON COLUMN SITE_USER.GENDER IS '성별';
COMMENT ON COLUMN SITE_USER.BIRTH_DT IS '회원 생년월일';


-- 회원 번호 시퀀스
CREATE SEQUENCE SEQ_USER_NO;


-- 게시판 종류 테이블 생성
CREATE TABLE BOARD_TYPE(
   BOARD_CD   NUMBER   PRIMARY KEY,
   BOARD_NM   VARCHAR2(50)   NOT NULL
);

-- 게시판 종류 테이블에 대한 커멘트
COMMENT ON COLUMN BOARD_TYPE.BOARD_CD IS '게시판 코드';
COMMENT ON COLUMN BOARD_TYPE.BOARD_NM IS '게시판 종류';

INSERT INTO BOARD_TYPE VALUES (1, '공지');
INSERT INTO BOARD_TYPE VALUES (2, '잡담');
INSERT INTO BOARD_TYPE VALUES (3, '칼럼');




-- 게시판 테이블 생성
CREATE TABLE BOARD (
   BOARD_NO   NUMBER   PRIMARY KEY,
   BOARD_TITLE   VARCHAR2(200)   NOT NULL,
   BOARD_CONTENT   VARCHAR2(4000)   NOT NULL,
   CREATE_DT   DATE DEFAULT SYSDATE NOT NULL,
   READ_COUNT   NUMBER DEFAULT 0 NOT NULL,
   BOARD_ST   CHAR(1)   DEFAULT 'N' NOT NULL,
   USER_NO   NUMBER   NOT NULL REFERENCES SITE_USER(USER_NO),
   BOARD_CD   NUMBER   NOT NULL REFERENCES BOARD_TYPE(BOARD_CD)
);

-- 게시판 테이블에 대한 커멘트
COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글 번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD.CREATE_DT IS '게시글 작성일';
COMMENT ON COLUMN BOARD.READ_COUNT IS '조회수';
COMMENT ON COLUMN BOARD.BOARD_ST IS '게시글 상태';
COMMENT ON COLUMN BOARD.USER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN BOARD.BOARD_CD IS '게시판 코드(FK)';

-- 게시글 번호 시퀀스
CREATE SEQUENCE SEQ_BOARD_NO;


-- 시즌 테이블 생성
CREATE TABLE SEASON (
   SEASON_NO   NUMBER   PRIMARY KEY,
   SEASON_NM   VARCHAR2(100)   NOT NULL
);

-- 시즌 테이블에 대한 커멘트
COMMENT ON COLUMN SEASON.SEASON_NO IS '시즌 번호';
COMMENT ON COLUMN SEASON.SEASON_NM IS '시즌 이름';

-- 국가 테이블 생성
CREATE TABLE NATION (
   NATION_NO   NUMBER   PRIMARY KEY,
   NATION_NM   VARCHAR2(50)   NOT NULL
);

-- 국가 테이블에 대한 커멘트
COMMENT ON COLUMN NATION.NATION_NO IS '국가 번호';
COMMENT ON COLUMN NATION.NATION_NM IS '국가 이름';

-- 등급 테이블 생성
CREATE TABLE RATING (
   RATING_NO   NUMBER   PRIMARY KEY,
   RATING_NM   VARCHAR2(50)   NOT NULL
);

-- 등급 테이블에 대한 커멘트
COMMENT ON COLUMN RATING.RATING_NO IS '등급 번호';
COMMENT ON COLUMN RATING.RATING_NM IS '등급 이름';



-- 영화 테이블 생성
CREATE TABLE MOVIE (
   MOVIE_NO   NUMBER   PRIMARY KEY,
   MOVIE_TITLE   VARCHAR2(90)   NOT NULL,
   MOVIE_OVERVIEW   VARCHAR2(2000)   NULL,
   RELEASE_DT   DATE   NULL,
   DURATION   NUMBER   NULL,
   MOVIE_POSTER   VARCHAR2(500)   NULL,
   NATION_NO   NUMBER REFERENCES NATION(NATION_NO) NOT NULL,
   RATING_NO   NUMBER REFERENCES RATING(RATING_NO) NOT NULL,
   SEASON_NO   NUMBER REFERENCES SEASON(SEASON_NO) NOT NULL
);

-- 영화 테이블에 대한 커멘트
COMMENT ON COLUMN MOVIE.MOVIE_NO IS '영화 번호';
COMMENT ON COLUMN MOVIE.MOVIE_TITLE IS '영화 제목';
COMMENT ON COLUMN MOVIE.MOVIE_OVERVIEW IS '줄거리';
COMMENT ON COLUMN MOVIE.RELEASE_DT IS '개봉일자';
COMMENT ON COLUMN MOVIE.DURATION IS '영화 시간';
COMMENT ON COLUMN MOVIE.MOVIE_POSTER IS '포스터';
COMMENT ON COLUMN MOVIE.NATION_NO IS '제작국가';
COMMENT ON COLUMN MOVIE.RATING_NO IS '영화등급';
COMMENT ON COLUMN MOVIE.SEASON_NO IS '시즌 번호';

-- 영화 번호 시퀀스
CREATE SEQUENCE SEQ_MOVIE_NO;







-- 댓글 테이블 생성
CREATE TABLE REPLY (
   REPLY_NO   NUMBER   PRIMARY KEY,
   REPLY_CONTENT   VARCHAR2(500)   NOT NULL,
   REPLY_DT   DATE DEFAULT SYSDATE NOT NULL,
   REPLY_ST   CHAR(1) DEFAULT 'N' NOT NULL,
   BOARD_NO   NUMBER REFERENCES BOARD(BOARD_NO) NOT NULL,
   USER_NO   NUMBER REFERENCES SITE_USER(USER_NO) NOT NULL
);

-- 댓글 테이블에 대한 커멘트
COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글 번호';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글 내용';
COMMENT ON COLUMN REPLY.REPLY_DT IS '댓글 작성일';
COMMENT ON COLUMN REPLY.REPLY_ST IS '댓글 상태';
COMMENT ON COLUMN REPLY.BOARD_NO IS '게시글 번호(FK)';
COMMENT ON COLUMN REPLY.USER_NO IS '회원 번호(FK)';


-- 댓글 번호 시퀀스
CREATE SEQUENCE SEQ_REPLY_NO;




-- 리뷰 테이블 생성
CREATE TABLE REVIEW (
   REVIEW_NO   NUMBER   PRIMARY KEY,
   S_CONTENT   VARCHAR2(500)   NOT NULL,
   L_CONTENT   VARCHAR2(2000)   NULL,
   REVIEW_RATING   NUMBER   NOT NULL,
   REVIEW_DT   DATE DEFAULT SYSDATE NOT NULL,
   REVIEW_ST   CHAR(1) DEFAULT 'Y' NOT NULL,
   USER_NO   NUMBER REFERENCES SITE_USER(USER_NO) NOT NULL,
   MOVIE_NO   NUMBER REFERENCES MOVIE(MOVIE_NO) NOT NULL
);

-- 리뷰 테이블에 대한 커멘트
COMMENT ON COLUMN REVIEW.REVIEW_NO IS '리뷰 번호';
COMMENT ON COLUMN REVIEW.S_CONTENT IS '리뷰 한줄평';
COMMENT ON COLUMN REVIEW.L_CONTENT IS '상세 리뷰';
COMMENT ON COLUMN REVIEW.REVIEW_RATING IS '리뷰 평점';
COMMENT ON COLUMN REVIEW.REVIEW_DT IS '리뷰 작성일';
COMMENT ON COLUMN REVIEW.REVIEW_ST IS '리뷰 상태';
COMMENT ON COLUMN REVIEW.USER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN REVIEW.MOVIE_NO IS '영화 번호(FK)';

-- 리뷰 번호 시퀀스
CREATE SEQUENCE SEQ_REVIEW_NO;

-- 영화 좋아요 테이블 생성
CREATE TABLE MOVIE_LIKE (
   USER_NO   NUMBER   NOT NULL REFERENCES SITE_USER(USER_NO),
   MOVIE_NO   NUMBER   NOT NULL REFERENCES MOVIE(MOVIE_NO),
   PRIMARY KEY (USER_NO, MOVIE_NO)
);
-- 영화 좋아요 테이블에 대한 커멘트
COMMENT ON COLUMN MOVIE_LIKE.USER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN MOVIE_LIKE.MOVIE_NO IS '영화 번호(FK)';

-- 게시글 추천 테이블 생성
CREATE TABLE BOARD_RECOM (
   BOARD_NO   NUMBER   NOT NULL REFERENCES BOARD(BOARD_NO),
   USER_NO   NUMBER   NOT NULL REFERENCES SITE_USER(USER_NO),
   PRIMARY KEY (BOARD_NO, USER_NO)
);

-- 게시글 추천 테이블에 대한 커멘트
COMMENT ON COLUMN BOARD_RECOM.BOARD_NO IS '게시글 번호(FK)';
COMMENT ON COLUMN BOARD_RECOM.USER_NO IS '회원 번호(FK)';



-- 장르 테이블 생성
CREATE TABLE GENRE (
   GENRE_NO   NUMBER   PRIMARY KEY,
   GENRE_NM   VARCHAR2(10)   NOT NULL,
   MOVIE_NO   NUMBER   NOT NULL REFERENCES MOVIE(MOVIE_NO)
);

-- 장르 테이블에 대한 커멘트
COMMENT ON COLUMN GENRE.GENRE_NO IS '장르 번호';
COMMENT ON COLUMN GENRE.GENRE_NM IS '장르 이름';
COMMENT ON COLUMN GENRE.MOVIE_NO IS '영화 번호(FK)';

-- 배우 테이블 생성
CREATE TABLE ACTOR (
   ACTOR_NO   NUMBER   PRIMARY KEY,
   ACTOR_NAME   VARCHAR2(500)   NOT NULL,
   MOVIE_NO   NUMBER   NOT NULL REFERENCES MOVIE(MOVIE_NO)
);



-- 배우 테이블에 대한 커멘트
COMMENT ON COLUMN ACTOR.ACTOR_NO IS '배우 번호';
COMMENT ON COLUMN ACTOR.ACTOR_NAME IS '배우 이름';
COMMENT ON COLUMN ACTOR.MOVIE_NO IS '영화 번호(FK)';

-- 배우 번호 시퀀스
CREATE SEQUENCE SEQ_ACTOR_NO;



-- 영화 스틸 이미지 테이블 생성
CREATE TABLE MOVIE_IMG (
   STILL_NO   NUMBER   PRIMARY KEY,
   STILL_IMG   VARCHAR2(500)   NOT NULL,
   MOVIE_NO   NUMBER   NOT NULL REFERENCES MOVIE(MOVIE_NO)
);

-- 영화 스틸 이미지 테이블에 대한 커멘트
COMMENT ON COLUMN MOVIE_IMG.STILL_NO IS '스틸 이미지 번호';
COMMENT ON COLUMN MOVIE_IMG.STILL_IMG IS '스틸 이미지';
COMMENT ON COLUMN MOVIE_IMG.MOVIE_NO IS '영화 번호(FK)';



-- 게시글 이미지 테이블 생성
CREATE TABLE BOARD_IMG (
   IMG_NO   NUMBER   PRIMARY KEY,
   BOARD_NO   NUMBER   NOT NULL REFERENCES BOARD(BOARD_NO),
   IMG_RENAME   VARCHAR2(500)   NOT NULL,
   IMG_ORIGINAL   VARCHAR2(500)   NOT NULL
);
-- 게시글 이미지 테이블에 대한 커멘트
COMMENT ON COLUMN BOARD_IMG.IMG_NO IS '이미지 번호';
COMMENT ON COLUMN BOARD_IMG.BOARD_NO IS '게시글 번호(FK)';
COMMENT ON COLUMN BOARD_IMG.IMG_RENAME IS '변경된 이미지 이름';
COMMENT ON COLUMN BOARD_IMG.IMG_ORIGINAL IS '원본 이미지 이름';


-- 게시글 이미지 번호 시퀀스
CREATE SEQUENCE SEQ_IMG_NO;

SELECT * FROM SITE_USER;

INSERT INTO SITE_USER
VALUES(SEQ_USER_NO.NEXTVAL,'user01','pass01','유저일','user01@naver.com',DEFAULT,DEFAULT,'user01','istp',
		'04540,,서울특별시 강남구 테헤란로 14길 6 5층',NULL,'M','1994-06-20');
	
ALTER TABLE SITE_USER MODIFY USER_PW VARCHAR2(100);	
COMMIT;
UPDATE SITE_USER SET
USER_PW ='02DeqFdlQnpEbQRZqnvpfK7a9sO9iISEV7Hzxntivto23dJ/i16UMur0ACYxwsfAxFwzfn5yarbQnsbAtkCJAg=='
WHERE USER_NO =1;

-- 회원 탈퇴
UPDATE SITE_USER SET
SECESSION_FL = 'Y'
WHERE USER_PW =? AND USER_NO =?;