--1
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE;
--2
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME)!=3;

--3 X 풀이 완
SELECT	PROFESSOR_NAME 교수이름,
			FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE(19||SUBSTR(PROFESSOR_SSN,1,6),'RRRRMMDD')) /12) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1)=1
ORDER BY 나이;


--4 X 풀이 완
SELECT SUBSTR( PROFESSOR_NAME,2) 이름
FROM TB_PROFESSOR; 

--5
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE	EXTRACT(YEAR FROM ENTRANCE_DATE) -
		EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN ,1,6), 'RRMMDD')) >19;

--6 X	
SELECT TO_CHAR(TO_DATE( '2020/12/25'), 'dy') FROM DUAL;	

--7

--8
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT

MINUS

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT 
WHERE STUDENT_NO LIKE 'A%';

--9
SELECT ROUND(AVG (POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';


--10
SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO 
ORDER BY DEPARTMENT_NO; 

--11
SELECT  COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12
SELECT	SUBSTR(TERM_NO,1,4) 년도, AVG(POINT) " 년도 별 평점"
FROM TB_GRADE
--WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4);
--ORDER BY 년도;

--13
-- 학과 별 휴학생 수를 파악하고자 한다. 학과 번호와 휴학생 수를 표시하는 SQL문장을 작성하시오
SELECT	DEPARTMENT_NO 학과코드명,
			COUNT(DECODE(ABSENCE_YN,'Y','Y','NO','N')) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 학과코드명;

SELECT	DEPARTMENT_NO 학과코드명,
			SUM(DECODE(ABSENCE_YN,'Y',1,'N',0)) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 학과코드명;
			
--14
--춘 대학교에 다니는 동명이인 학생들의 이름을 찾고자 한다.
-- 어떤 SQL 문장을 사용하면 가능하겠는가?
SELECT	STUDENT_NAME 동일이름,
			COUNT(*) "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME 
HAVING COUNT(*)>1
ORDER BY STUDENT_NAME;

--15
-- 학번이 A112113인 금고운 학생의 년도, 학기 별 평점과 년도 별 누적 평점, 
-- 총 평점을 구하는 SQL문을 작성하시오
-- (단, 평점은 소수점 1자리까지만 반올림하여 표시한다.)

SELECT	NVL(SUBSTR(TERM_NO,1,4),' ') 년도,
			NVL(SUBSTR(TERM_NO,5,2),' ')학기,
			ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4) , SUBSTR(TERM_NO,5,2));